#! /bin/sh

usage="Dump database from a container

Usage:
  $(basename "$0") CONTAINER
  $(basename "$0") -h
"

if [ "$#" -ne 1 ]; then
  echo "$usage" >&2
  exit 1
fi

while getopts ':h:' option; do
  case "$option" in
    h) echo "$usage"
      exit
      ;;
    \?) printf "illegal option: -%s\n" "$OPTARG" >&2
      echo "$usage" >&2
      exit 1
      ;;
  esac
done

echo "💾 Dump db from container $1..."

file_name="$1_$(date "+%F_%H-%M-%S").sql"

if docker exec $1 sh -c 'command -v pg_dump >> /dev/null'; then
  docker exec $1 sh -c 'pg_dump $POSTGRES_DB -U $POSTGRES_USER --clean' > "$file_name" || exit 1
elif docker exec $1 sh -c 'command -v mysqldump >> /dev/null'; then
  docker exec $1 sh -c 'mysqldump -u $MYSQL_USER --password="$MYSQL_PASSWORD" $MYSQL_DATABASE' > "$file_name" || exit 1
else
  echo "❌ Not a supported db"
  exit 1
fi
echo "✅ Dump db stored in $file_name..."
